### ISSUE TITLE
Perhaps I am the first to give you a message and advice.^0^

### ISSUE THREAD

**Issue by alenhrp** [602387193c/ComfyUI-wiki#6]
The content is wonderfully organised!
It is suggested to add the introduction of ResAdapter and Hidiffusion, mainly for Unlocking Higher-Resolution Creativity and Efficiency, which has a great improvement and user concerns and application prospects.

**Comment by 602387193c** [comment]
谢谢你的建议。我稍后把你说的加进去，我还真没想到会有人提issues呢。也没注意看。
