### ISSUE TITLE
节点缺失

### ISSUE THREAD

**Issue by LongKaiAAA** [602387193c/ComfyUI-wiki#9]
导入anytext-一键12套工作流后，发现还存在一个节点爆红，但是在ComfyUI-Manager中未显示缺失的节点是什么，想问下这个缺失的节点是什么
<img width="1280" alt="1723605424113" src="https://github.com/user-attachments/assets/a4588a00-9a57-4738-a9e9-d60698f832a7">

**Comment by 602387193c** [comment]
这anytext的实用性不强，可以看看我的另外一个
https://www.bilibili.com/video/BV1zEpSeWEDE/?vd_source=7351bb1ce0a307c41b60b64ca036a240
